# Generated by Django 3.2.11 on 2022-01-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataevent',
            name='element',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dataevent',
            name='host',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dataevent',
            name='path',
            field=models.CharField(max_length=250),
        ),
    ]
