# Generated by Django 3.2.11 on 2022-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0002_auto_20220121_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataevent',
            name='element',
        ),
        migrations.AddField(
            model_name='dataevent',
            name='rest_data',
            field=models.JSONField(blank=True, db_index=True, default={}),
            preserve_default=False,
        ),
    ]
