# Generated by Django 3.2.11 on 2022-01-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0003_auto_20220121_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataevent',
            name='rest_data',
            field=models.JSONField(blank=True),
        ),
    ]
