# Generated by Django 3.2.11 on 2022-01-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0004_alter_dataevent_rest_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='DataEvent',
        ),
    ]
