# Generated by Django 3.2.11 on 2022-01-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0005_auto_20220122_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='session',
            new_name='session_id',
        ),
    ]
